name: snowflake-migration-demo # name of the workflow

# Controls when the action will run
on:
  push:
    branches:
      - main
    paths:
      - 'deploy-files/**'
  
  # Allows you to run the workflow from github actions
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under the $GITHUB_WORKSPACE, so that your job can access it.
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT}}
          SF_USERNAME: ${{ secrets.SF_USERNAME}}
          SF_ROLE: ${{ secrets.SF_ROLE}}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE}}
          SF_DATABASE: ${{ secrets.SF_DATABASE}}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD}}

        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing Schema Change"
          pip install schemachange

          echo "Step 2: Running Schema Change"
          schemachange -f $GITHUB_WORKSPACE/deploy-files -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
